### ISSUE TITLE
kubernetes UI and Component health

### ISSUE THREAD

**Issue by Smithx10** [fayazg/tritonK8ssupervisor#6]
@fayazg ,

I am new to K8s and Rancher, but it seems this repo bootstrapped with the following issues.

and When browsing to http://10.1.106.102:8080/r/projects/1a45/kubernetes-dashboard:9090/#

I receive the folllowing message: 
Service Unavailable

> kubectl get componentstatus
NAME                 STATUS      MESSAGE
        ERROR
scheduler            Unhealthy   Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: getsockopt: connection re
fused
controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection re
fused
etcd-0               Healthy     {"health": "true"}

note:  I am running this on my own on prem triton,  but I believe this is app level and not any issue with my configuration.    Perhaps there might be something for me to check.

Thank You,
Bruce Smith

**Comment by fayazg** [comment]
Have you tried restarting the Kubernetes dashboard container?

Can you go to infrastructure containers page for your Kubernetes environment in rancher (this would be the first url you get after the setup completes):
    http://10.1.106.102:8080/env/1a45/infra/containers
And see if all containers are up?
You should see a few that are stopped, that is fine, we want to confirm if you have two running containers **kubernetes-dashboard** and another that starts with **kubernetes-dashboard** followed by some numbers and letters. Restart or delete the second one.

**Comment by fayazg** [comment]
#7 Dashboard should restart if it gets stuck.
